# Generated by Django 3.1.1 on 2020-09-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'Tweets'},
        ),
    ]
