# Generated by Django 3.1.1 on 2020-11-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20201116_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetfile',
            old_name='file',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='file_content',
        ),
        migrations.AddField(
            model_name='tweetfile',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweets'),
        ),
    ]
