# Generated by Django 3.1.1 on 2020-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200927_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='comment_images'),
        ),
        migrations.AddField(
            model_name='tweets',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
