# Generated by Django 3.1.1 on 2020-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20201119_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetfile',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweets',
            name='file_content',
            field=models.ManyToManyField(related_name='file_content', to='tweets.TweetFile'),
        ),
    ]
