# Generated by Django 3.1.1 on 2020-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200930_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='user_like',
            new_name='liker',
        ),
    ]
