# Generated by Django 3.1.1 on 2020-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20201119_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='file_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='file_content', to='tweets.TweetFile'),
        ),
    ]
