# Generated by Django 3.1.1 on 2020-09-30 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0007_auto_20200930_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_liker',
            field=models.ManyToManyField(related_name='comment_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
