# Generated by Django 3.1.1 on 2020-11-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0007_auto_20201120_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='file_content',
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_media', models.FileField(upload_to='comment_images')),
                ('tweep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_files',
            field=models.ManyToManyField(related_name='comment_file_content', to='tweets.CommentFile'),
        ),
    ]
