# Generated by Django 3.1.1 on 2020-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20201124_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_file_content', to='tweets.CommentFile'),
        ),
    ]
