# Generated by Django 3.1.1 on 2020-12-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_followers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_following',
            field=models.BigIntegerField(default=0),
        ),
    ]
